services:
  export:
    image: node:16-alpine
    command: sh -c "npm run build && npm run db:setup -- -f && npm run export -- --no-webhooks"
    working_dir: /usr/src/app
    ports:
      - 9227:9227 # debug
    volumes:
      # use local files as source
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      # contains db connection info that matches db service setup below
      CONFIG_FILE: config-dev.json
    # waits for db to start
    depends_on:
      db_accounts:
        condition: service_healthy
      db_data:
        condition: service_healthy
    # colorizes output
    tty: true

  db_accounts:
    image: postgres:14-alpine
    # matches config in config-dev.json
    environment:
      POSTGRES_DB: dev_accounts
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d dev_accounts -U dev']
      interval: 1s
      timeout: 3s
      retries: 5

  db_data:
    image: postgres:14-alpine
    # matches config in config-dev.json
    environment:
      POSTGRES_DB: dev_data
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d dev_data -U dev']
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  node_modules:
